name: Delete Skin
title: Delete Skin
description: Delete Your Current Skin
labels:
  - delete
body:
  - type: checkboxes
    attributes:
        label: Delete Skin
        description: Submit this issue to delete your current skin!
        options: []